{{- if or .Values.global.ghcrSecret.enabled (ne .Values.global.ghcrSecret.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.ghcrSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "dockerconfigjson" . | b64enc }}
{{- end }}
