apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-config-js
data:
  config.js: |
    window.APP_CONFIG = {
      VITE_API_URL: {{ printf "http://api-zoo-%s.example.com:%d" .Release.Namespace (.Values.global.ingress.port | int) | quote }},
    };
