apiVersion: v2
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-config
data:
  API_URL: {{ printf "http://%s-backend:%d" .Release.Name (.Values.backend.port | int) | quote }}
{{- with .Values.global.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
