apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-config
data:
  VITE_API_URL: {{ printf "http://zoo-backend-%s-backend:%d" .Release.Namespace (.Values.backend.port | int) | quote }}
{{- with .Values.global.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
