apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-frontend
spec:
  rules:
    - host: {{ tpl .Values.ingress.hostTemplate . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-{{ .Release.Namespace }}-frontend
                port:
                  number: {{ .Values.service.port }}
