image:
  name: zoo-frontend
  tag: "latest"
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  hostTemplate: "zoo-{{ .Release.Namespace }}.example.com"
backend:
  port: 3000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
