apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-secret
  labels:
    app.kubernetes.io/name: zoo-mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.root.user | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.root.password | quote }}
