apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-svc
  labels:
    app.kubernetes.io/name: zoo-mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: zoo-mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
