global:
  replicas: 1
  env:
    NODE_ENV: production
    YARN_CACHE_FOLDER: .cache
  image:
    repository: ghcr.io/vieites-tfg
    pullPolicy: Always
  ghcrSecret:
    enabled: false
    name: ghcr-secret
    registry: ghcr.io
    username: vieites
    password: "" # From cmd line
  ingress:
    port: 8080

