global:
  # replicas: 2
  env:
    NODE_ENV: production

zoo-frontend:
  image:
    tag: "0.0.0"
  ingress:
    hostTemplate: "zoo-pro.example.com"

zoo-backend:
  image:
    tag: "0.0.0"
  mongo:
    service:
      name: "zoo-mongo-pro-svc"
  ingress:
    hostTemplate: "api-zoo-pro.example.com"

zoo-mongo:
  internal:
    enabled: true
  external:
    enabled: false
