// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"sort"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/cd/internal/dagger"
	"dagger/cd/internal/querybuilder"
	"dagger/cd/internal/telemetry"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Cd) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Socket      *dagger.Socket
		KindSvc     *dagger.Service
		ClusterName string
		ConfigFile  *dagger.File
	}
	concrete.Socket = r.Socket
	concrete.KindSvc = r.KindSvc
	concrete.ClusterName = r.ClusterName
	concrete.ConfigFile = r.ConfigFile
	return json.Marshal(&concrete)
}

func (r *Cd) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Socket      *dagger.Socket
		KindSvc     *dagger.Service
		ClusterName string
		ConfigFile  *dagger.File
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Socket = concrete.Socket
	r.KindSvc = concrete.KindSvc
	r.ClusterName = concrete.ClusterName
	r.ConfigFile = concrete.ConfigFile
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	var gqlErr *gqlerror.Error
	if errors.As(rerr, &gqlErr) {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		var exec *dagger.ExecError
		if errors.As(err, &exec) {
			return exec.Unwrap()
		}
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Cd":
		switch fnName {
		case "Base":
			var parent Cd
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Cd).Base(&parent), nil
		case "Cluster":
			var parent Cd
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Cd).Cluster(&parent, ctx), nil
		case "Launch":
			var parent Cd
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var secEnv *dagger.File
			if inputArgs["secEnv"] != nil {
				err = json.Unmarshal([]byte(inputArgs["secEnv"]), &secEnv)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg secEnv", err))
				}
			}
			var helmfile *dagger.File
			if inputArgs["helmfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["helmfile"]), &helmfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg helmfile", err))
				}
			}
			return (*Cd).Launch(&parent, ctx, secEnv, helmfile)
		case "":
			var parent Cd
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var socket *dagger.Socket
			if inputArgs["socket"] != nil {
				err = json.Unmarshal([]byte(inputArgs["socket"]), &socket)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg socket", err))
				}
			}
			var kindSvc *dagger.Service
			if inputArgs["kindSvc"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kindSvc"]), &kindSvc)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kindSvc", err))
				}
			}
			var clusterName string
			if inputArgs["clusterName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["clusterName"]), &clusterName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg clusterName", err))
				}
			}
			var configFile *dagger.File
			if inputArgs["configFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["configFile"]), &configFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg configFile", err))
				}
			}
			return New(socket, kindSvc, clusterName, configFile), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Cd", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 9, 6)}).
					WithFunction(
						dag.Function("Base",
							dag.TypeDef().WithObject("Container")).
							WithSourceMap(dag.SourceMap("main.go", 50, 1))).
					WithFunction(
						dag.Function("Cluster",
							dag.TypeDef().WithObject("Container")).
							WithSourceMap(dag.SourceMap("main.go", 66, 1))).
					WithFunction(
						dag.Function("Launch",
							dag.TypeDef().WithObject("Container")).
							WithSourceMap(dag.SourceMap("main.go", 102, 1)).
							WithArg("secEnv", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{Description: "`.env` file with the credentials to use the private images and the variables\nrelated to the mongo database.", SourceMap: dag.SourceMap("main.go", 108, 2)}).
							WithArg("helmfile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "`helmfile.yaml` necessary to launch the chart.", SourceMap: dag.SourceMap("main.go", 112, 2)})).
					WithField("Socket", dag.TypeDef().WithObject("Socket"), dagger.TypeDefWithFieldOpts{Description: "Docker socket to connect to the external Docker Engine. Please carefully\nuse this option it can expose your host to the container.\nE.g. /var/run/docker.sock", SourceMap: dag.SourceMap("main.go", 14, 2)}).
					WithField("KindSvc", dag.TypeDef().WithObject("Service"), dagger.TypeDefWithFieldOpts{Description: "It should be the tcp://127.0.0.1 followed by any port.\nE.g. tcp://127.0.0.1:3000", SourceMap: dag.SourceMap("main.go", 19, 2)}).
					WithField("ClusterName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.TypeDefWithFieldOpts{Description: "The name for the cluster.", SourceMap: dag.SourceMap("main.go", 23, 2)}).
					WithField("ConfigFile", dag.TypeDef().WithObject("File"), dagger.TypeDefWithFieldOpts{Description: "The name for the cluster.", SourceMap: dag.SourceMap("main.go", 27, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Cd")).
							WithSourceMap(dag.SourceMap("main.go", 30, 1)).
							WithArg("socket", dag.TypeDef().WithObject("Socket"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 31, 2)}).
							WithArg("kindSvc", dag.TypeDef().WithObject("Service"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 32, 2)}).
							WithArg("clusterName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 34, 2)}).
							WithArg("configFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 36, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
