root := "../.."
sops := "../../sops"
cluster := "../../cluster"

_default:
  just -l

deploy:
  dagger call \
    --socket=/var/run/docker.sock \
    --kind-svc=tcp://localhost:3000 \
    --config-file=file://{{cluster}}/kind_local.yaml \
    deploy \
    --sec-env=file://{{root}}/.env \
    --env="dev" \
    --age-key=file://{{sops}}/age.agekey \
    --sops-config=file://{{sops}}/.sops.yaml

cluster *more:
  dagger call \
    --socket=/var/run/docker.sock \
    --kind-svc=tcp://localhost:3000 \
    --config-file=file://{{cluster}}/kind_local.yaml \
    cluster {{more}}
